인스타 그램 PR
Roy-wonji/DevlopGram pull request #7
Opened 2022-06-05 11:35 UTC by Roy-wonji

### 안녕하세요 @yeahg-dev
소중한 시간 내어 리뷰를 맡아주셔서 감사드립니다!😃
pr 요청을 부탁드렸는데 해주셔서 감사해요
진행하며 어려웠던 점과 고민되었 던 점을 정리해보았습니다.
한 번 읽어보시고 조언 주시면 정말 감사하겠습니다!
인스타그램 클론 프로젝트 STEP3 pr 요청 드립니다
잘부탁드립니다 !!

----
### 실행 영상

![KakaoTalk_Video_2022-06-04-14-46-18](https://user-images.githubusercontent.com/75601594/172039802-705b4a6f-d709-478e-a167-1e691f9eca6b.gif)

### 구현내용
- 코드 베이스로 UI구현
- 앱을 비동기 동기 과정을 사용해서 구현
- MVVM 디자인 패턴을 사용해서 앱을 최대한 클린 아키텍쳐로 구현
- UICollectioview를 코드로 구현
- 파이어 베이스 연동 및 podfile을 사용해서 앱에 추가하는 걸 구현
- 검색창에 등록한 프로필 구현 
- 프로필을 누르면 업로드한 사진 별로 올라가게 구현
- 검색할때 이름 순으로 필터를 걸어서 구현
- 다크모드 구현
- 로그인 한 계정이 다른경우 프로필 사진및 이름이 변경하게 구현
- 피드를 올리면  올린 계정에 이름이랑  피드 사진및 글이 올라가게 구현
- 댓글을 달면  댓글 단 계정 및 이름이 timestamp로 나오게 구현 
- 좋아요를 누리면 계시글에 좋아요 카운트가 증가하면서 버튼 색상이 바뀌게 구현 

### 고민했던점 && 로직구현

- 처음으로 mvc 말고 mvvm 디자인 패턴으로 구현을 하려고 하니까 view model안에는 어떤 로직을 구현을 해야 하는 어려웠습니다 . ㅠㅠㅠㅠ
- 앱을 동작을 했을때 로그인이 되면 메인 화면으로 보이고 아니면 로그인 화면으로 구현 하는 방식을 어떨게 할지 고민을 했습니다.
- 메인쓰레드에서 앱에 정보가 많아지면 앱이 버벅일수 있어서 버벅이는 걸 방지 하기 위해서 비동기 동기 프로그램을 사용해서 앱이 버벅이지 않고 구현을 하도록 했습니다.
- 파이어베이스 연동및 로그인했을때 api를 연동을 하면서 데이터를 받아오고 넘겨주는 부분은 네트워킹에 api 라는 파일 구현 해서 최대한 분리 하면서 구현을 했습니다 .
- 최대한 한 파일안에 한 구조체 및 클래스가 사용하려고 노력을 하면서 , 하드코딩을 피하면서 최대한 클린 아키텍쳐로 구현을 했습니다.
- 프로필로 가서 사진 이 다르게 나오게 구현을 할려면 사진이 조금 늦게 올라오는건 사진이 업로드 하는과정에서 비동기적이 작업을 해야되서 비동기적인 작업을 구현을 했습니다.
- table뷰에 가입한 계정및 이름이 순서대로 나오게 구현 및 이름을 순서대로 구현하면서 map을 핕터를 걸면서 구현을 했습니다.
- 다크 모드를 구현을 할때 각 컬러의 set을 설정해주면서 컬러를 구현을 했습니다
- 다른계정으로 로그인을 하면 로그인 한 계정이름 , 사진 이 업로드 하게 되게 구현및 사진이 업로드 할때는 비동기 처리로 구현을 했습니다.
- 좋아요를 눌었을때 색상을 변경하고 카운트 수 증가를 뷰델에서 구현을 했습니다 

### 사진 업로드 및 뷰모델에서 가져오는경우  
 메인 뷰에서 관리하는 작업 같은경우는 비동기 적으로 한번 더 처리를 해주었는데  

```swift
  private func configure( ) {
        DispatchQueue.main.async {
            guard let viewModel = self.viewModel else { return }
            self.captionLabel.text = viewModel.caption
            self.postImageView.sd_setImage(with: viewModel.imageUrl)
            self.profileImageView.sd_setImage(with: viewModel.userProfileImageUrl)
            self.userNameButton.setTitle(viewModel.username, for: .normal)
            self.likesLabel.text = viewModel.likesLabelText
            self.likeButton.tintColor = viewModel.likeButtonTintColor
            self.likeButton.setImage(viewModel.likeButtonImage, for: .normal)
        }
    }
```
이렇게 감싸 주는게 쓰레드및 동기적으로 작업이 됏다고 생각을 하면 될까요? 
이렇게 하는 방식이 맞는지 해서용 ???

### API
연결해야 하는 api가 많은 경우 api 별로 파일을 분리 해서 하고 싶은데 제가 하고있는 방식이 맞는지 해서 릴리의 생각 및 의견이 궁금합니다 
result 처리를 api에서 처음해보았는데 이렇게 하는 방식이 맞나요??
```swift
struct AuthService {
    static func logUseIn(withEmail email: String, password: String, completion:   @escaping(AuthDataResult?, Error?) -> Void) {
        Auth.auth().signIn(withEmail: email, password: password, completion: completion)
    }
    
    static func registerUser(withCredential credentials: AuthCredentials,  completion:
                             @escaping(Error?) -> Void) {
        ImageUploader.uploadImage(image: credentials.profileImage) { imageUrl in
            Auth.auth().createUser(withEmail: credentials.email, password: credentials.password) { (result,  error) in
                
                if let error = error {
                    print("DEBUG: Falied to register user \(error.localizedDescription)")
                    return
                }
                guard let uid = result?.user.uid else { return }
                let data: [String: Any] = ["email": credentials.email,
                                           "fullname": credentials.fullname ,
                                           "profileImageUrl": imageUrl,
                                           "uid": uid,
                                           "username": credentials.username]
                Constants.COLLECTION_USERS.document(uid).setData(data, completion: completion)
            }
        }
    }
}
```

### 뷰모델이 커진 상황
각 컨트롤러 마다 뷰모델 코드가 생기면서 코드가 엄청 많아졌습니다 ㅠㅠㅠㅠ
뷰모델에서 어떤걸 처리 해야 되나하는 릴리에 생각이 궁금합니다 

![1](https://user-images.githubusercontent.com/75601594/172039718-e64eb964-4bea-4859-a0d3-4ab32546561f.jpg)

[jira 협어툴을 사용해보았어요](https://royteam.atlassian.net/projects/HVUL?selectedItem=com.xiplink.jira.git.jira_git_plugin__project-centric-gitCommits-link-to-panel&issue.key=&project.key=HVUL)

#1 프로필에 데이터 받아오기
#2 feed이미지 업로드
#3 계시글에 댓글 달기

2022-06-07 06:08 UTC, yeahg-dev approved these changes
'APPROVE' performed by Xcode.

2022-06-07 16:54 UTC, yeahg-dev requested changes
안녕하세요 로이!
역할별로 함수와 객체를 잘 분리해주셔서 큰 규모임에도 이해하기 수월했던 것 같아요
그리고 코드로 UI를 능수능란하게 잘 작성하시는군요👍✨

저도 이제 막 MVVM+클린아키텍처를 공부하는 입장이라 리뷰 준비하면서 MVVM은 무엇인가에 대해 공부해본 좋은 기회였습니다!
제가 남기는 의견은 MVVM + 클린을 구현하는 방법 중 하나로 저의 생각이니, 다른 의견이 있으시다면 솔직하고 편하게 말씀해주세요~!

## 고민하신 부분에 대한 답변

### TabBarController 설정관련 코드는 어디에서 호출해야하는지

음... 이 부분에 대해선 로이의 생각이 먼저 궁금한데요~
TabBar의 설정 함수의 호출 위치를 `SceneDelegate`와 `TabBarController` 두 군데로 고민하셨는데, `SceneDelegate`를 고민하신 이유는 무엇이고,  `TabBarController`에서 호출한 이유는 무엇인지 궁금합니다!

<br>

### ViewModel의 역할

클린아키텍쳐에서 뷰는 뷰모델을 소유합니다. 뷰모델은 뷰로부터 이벤트를 받고,  유스케이스에서 API를 호출하여 전달받은 데이터를 뷰에 바로 뿌려줄 수 있는 형식으로 포맷팅을 하는 역할을 담당한다고 생각합니다. 특정 뷰에 보여지는 데이터를 제공하기 때문에, 뷰모델은 뷰에 종속적이지만, 뷰와 모델의 의존성을 없애주기 때문에 UI와 비지니스 로직을 분리 할 수 있고 유연한 설계를 가능하게 하고요.

제가 생각하는 뷰모델의 역할인 2가지가 로이만의 방법으로 달성되었다고 생각합니다.

1. 뷰에 보여질 데이터를 처리하는 역할
2. 바인딩을 통해 수동적인 뷰를 만든다

다만 개선되었으면 하는 부분이 있다면, 라인별 코멘트에도 남겼지만 뷰가 API를 호출하는 경우입니다. 뷰모델을 거치지 않고 뷰가 직접 API를 참조하게 되면 뷰와 API사이에는 의존성이 생깁니다. 뷰모델을 만들어서 의존성을 낮추고 책임을 분리해주세요!

<br>

### UI처리시 `main.async`를 사용하는 것

```
  private func configure( ) {
        DispatchQueue.main.async {
            guard let viewModel = self.viewModel else { return }
            self.captionLabel.text = viewModel.caption
            self.postImageView.sd_setImage(with: viewModel.imageUrl)
            self.profileImageView.sd_setImage(with: viewModel.userProfileImageUrl)
            self.userNameButton.setTitle(viewModel.username, for: .normal)
            self.likesLabel.text = viewModel.likesLabelText
            self.likeButton.tintColor = viewModel.likeButtonTintColor
            self.likeButton.setImage(viewModel.likeButtonImage, for: .normal)
        }
    }

```

`configure`가 호출되는 스레드가 메인스레드가 아닌 글로벌스레드라면 `DispatchQueue.main.async`로 감싸주시면 작성하신 것이 맞습니다:)

<br>

## 추가적으로 의견 드리고 싶은 점

### 클린아키텍처

제가 공부했던 클린아키텍처 레퍼런스들에서는 API Service는 Usecase(비지니스로직)가 소유했었습니다. 그래서 뷰에서 API를 들고 호출하는 구조가 어색하게 느껴졌던 것 같아요.

현재 소프트웨어의 각 객체들이 [클린아키텍쳐](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html)의 Entity, Usecase, Presentaion 어떤 레이어에 속하나요?

각 레이어간의 의존성에 대해 고민하고 Usecase를 추가해서 역할을 분리해보면 더 클린아키텍쳐스러워질 것 같습니다!

## 파일구조
파일 구조가 현재는 Model / ViewModel / Controller.. 로 크게 MVVM으로 나뉘어져있는데요. 각 Scene과 연관된 뷰 컨트롤러와 뷰모델, 뷰 컴포넌트가 분리되어 있어서 찾기가 조금 어려운 것 같네요🤔
Sceme별로 연관된 뷰와 뷰모델을 모아두는 방법도 있으니 참고해보시는 것도 좋을 것 같습니다~

그리고 뷰 클래스들 중 `UI`카테고리로 들어가있는 친구들은 왜 따로 분리해뒀는지 이유가 궁금합니다

2022-06-07 16:54 UTC, yeahg-dev commented on instagram/instagram/Controllers/TabBarController/ImageSelector/UploadPostController.swift
> +            PostService.uploadPost(caption: caption, image: image) { error  in
메인스레드에서 API를 호출하고 있는 것 같습니다.
통신은 글로벌 큐로 보내어서 메인 큐는 UI업데이트 처리에 집중할 수 있도록 하는 건 어떨까요?

2022-06-07 16:54 UTC, yeahg-dev commented on instagram/instagram/Utills/Extensions/Extensions.swift
> +                height: CGFloat? = nil) {
짧고 간단하게 뷰에 제약을 줄 수 있는 좋은 익스텐션이네요👍

2022-06-07 16:54 UTC, yeahg-dev commented on instagram/instagram/API/FireBaseAPI/Constants.swift
> +}
`Constants`보다는 타입의 역할을 설명하는 구체적인 이름을 지어주면 가독성이 더 향상 될 수 있을 것 같네요!

2022-06-07 16:54 UTC, yeahg-dev commented on instagram/instagram/VIew/Common/CellIdentifier.swift
> +    static let headerIdentifier = "ProfileHeader"
아래에서 `register`와 `dequeReusableCell`익스텐션은 Cell 클래스 이름을 CellIdentifier로 사용할 수 있어서 편리하답니다~! 참고해보세요! 

https://github.com/SwifterSwift/SwifterSwift/blob/master/Sources/SwifterSwift/UIKit/UICollectionViewExtensions.swift

2022-06-07 16:54 UTC, yeahg-dev commented on instagram/instagram/Controllers/TabBarController/MainTabViewController.swift
> +    //MARK: tabbar 의 이미지가 선택 되었을때랑 안선택 되었을때 이미지 선택 해주는 함수
MARK와 코드블럭 사이의 띄어쓰기에 대한 컨벤션을 정하고 통일시켜주세요😊

2022-06-07 16:54 UTC, yeahg-dev commented on instagram/instagram/Controllers/Authentication/RegisterView/RegistrationController.swift
> +    private func setConstrantsStackVIew() {
오타가 있네요👀 contraints입니다~!

2022-06-07 16:54 UTC, yeahg-dev commented on instagram/instagram/Controllers/TabBarController/Profile/ProfileController.swift
> +            self.collectionView.reloadData()
각 메서드마다 `reloadData`를 호출해주신 이유가 있을까요?

컬렉션뷰의 `reloadData`는 부하가 큰 메서드로 알고 있습니다. 그런데 `checkIfUserIsFollowed`와 `fetchUserStatus` `fetchPosts`에서 각각 모두 `reloadData` 호출하고 있네요. `updateAPI`에서 3개의 메서드를 모두 호출하면 `reloadData`가 총 3번 호출되는데, 이 로직을 좀 더 개선시킬 수도 있을 것 같습니다.

2022-06-07 16:54 UTC, yeahg-dev commented on instagram/instagram/Controllers/TabBarController/Profile/ProfileController.swift
>      }
뷰가 API서비스를 참조하고 있습니다. 클린아키텍처+MVVM구조에서는 Usecase가 API를 참조하여 사용하고, 받은 데이터를 뷰모델로 보내어 해당 뷰에 알맞은 형식으로 변환하여 뷰에 최종적으로 바인딩합니다. 이렇게 함으로써 뷰와 API의 의존성을 낮출 수 있고, 변화가 쉽고 확장 가능하다는 장점이 있다고 생각합니다. 

Usecase를 두어서,  더 클린아키텍쳐스럽게 구현해보는 건 어떨까요?

2022-06-07 16:54 UTC, yeahg-dev commented on instagram/instagram/VIew/TabBarCell/Profile/ProfileHeader.swift
> +    }
띄어쓰기 컨벤션을 맞춰주세요!

2022-06-07 16:54 UTC, yeahg-dev commented on instagram/instagram/Utills/Extensions/AuthService.swift
> +                }
UI를 통해 사용자에게 까지 알려주어야하는 에러라고 생각하는데, 로이 생각은 어떤가요?

2022-06-08 03:45 UTC, Roy-wonji commented on instagram/instagram/Utills/Extensions/AuthService.swift
> +                }
그럴경우는  알림창을 구현해서 사용자에게 알려주어야  할거 같아요 ㅎㅎㅎ

2022-06-08 05:00 UTC, Roy-wonji commented on instagram/instagram/VIew/TabBarCell/Profile/ProfileHeader.swift
> +    }
넵!!

2022-06-08 07:33 UTC, Roy-wonji commented on instagram/instagram/Controllers/TabBarController/MainTabViewController.swift
> +    //MARK: tabbar 의 이미지가 선택 되었을때랑 안선택 되었을때 이미지 선택 해주는 함수
넵!!!

2022-06-08 07:36 UTC, Roy-wonji commented on instagram/instagram/Utills/Extensions/Extensions.swift
> +                height: CGFloat? = nil) {
넵  감삼합니다 ㅎㅎㅎ

2022-06-08 07:44 UTC, Roy-wonji commented
@yeahg-dev  

TabbarController를 SceneDelegate 에서 호출 하는 이유는 어떤 scene을 rootviewcontroller로 지정할때  같이 tabbarcontroller를 할수 있어서 SceneDelegate에서 바로 호출 한다는생각 때매  SceneDelegate에서 호출 한다는 생각을 했습니다 

TabBarControlle에서 하면  viewdidload에서 호출을 하면서 할수 있다고 생각이 들었습니다

2022-06-08 07:45 UTC, Roy-wonji commented on instagram/instagram/Controllers/TabBarController/ImageSelector/UploadPostController.swift
> +            PostService.uploadPost(caption: caption, image: image) { error  in
오  거기까지 생강을  못했습니다 감사합니다!

2022-06-08 07:55 UTC, Roy-wonji commented on instagram/instagram/Controllers/TabBarController/MainTabViewController.swift
> +    //MARK: tabbar 의 이미지가 선택 되었을때랑 안선택 되었을때 이미지 선택 해주는 함수
넵!!

2022-06-08 07:55 UTC, Roy-wonji commented on instagram/instagram/VIew/Common/CellIdentifier.swift
> +    static let headerIdentifier = "ProfileHeader"
@yeahg-dev  말한대로 수정을 했습니다

2022-06-08 08:02 UTC, Roy-wonji commented on instagram/instagram/Controllers/TabBarController/ImageSelector/UploadPostController.swift
> +            PostService.uploadPost(caption: caption, image: image) { error  in
넵  그게  더 좋은거 같아요!

2022-06-08 08:10 UTC, Roy-wonji commented on instagram/instagram/Controllers/TabBarController/Profile/ProfileController.swift
> +            self.collectionView.reloadData()
맨처응에는 다 호출해주어야 된다고 생각해서 `reloadData`를 다 호출 해준거 같아여  @yeahg-dev  말을들어보니 upadteAPI가 호출 하고 잇으니  updateAPI에서 호출해주는 게 맞는거 같아요!!  반영했습니다

2022-06-08 11:02 UTC, Roy-wonji commented on instagram/instagram/Controllers/TabBarController/Profile/ProfileController.swift
>      }
넵  반영해서 수정했어욯ㅎㅎ

2022-06-09 13:13 UTC, merged